mt = float(input('digite a distância em METROS: '))
print('Em KM vale {}'.format(mt / 1000))
print('Em HM vale {:.3f}'.format(mt / 100))
print('Em DAM vale {:.2f}'.format(mt / 10))
print('Em M vale {}'.format(mt))
print('Em DM vale {}'.format(mt * 10))
print('Em CM vale {:.0f}'.format(mt * 100))
print('Em MM vale {:.0f}'.format(mt * 1000))
